Feature/initialization
wecode-bootcamp-korea/36-1st-wesely-backend pull request #1
Opened 2022-08-16 08:15 UTC by seatbelt92

##  초기환경세팅

2022-08-16 09:49 UTC, kyeongraekim requested changes

2022-08-16 09:49 UTC, kyeongraekim commented on .gitignore
> +.vscode
맥 유저라면 나도 모르는 사이에 함께 올라 올 수 있는 .DS_Store 숨김파일도 깃 이그노어에 함께 추가해주세요!~

2022-08-16 09:49 UTC, kyeongraekim commented on package.json
> +    "typeorm": "^0.3.7"
mysql driver 설치 없이도 잘 돌아가는지 궁금하네요! 런서버 성공 이미지 파일을 함께 이미지 첨부파일로 올려주세요!~

2022-08-16 10:37 UTC, lordmyshepherd requested changes

2022-08-16 10:37 UTC, lordmyshepherd commented on package.json
> +    "nodemon": "^2.0.19",
nodemon은 devDependencis 혹은 global에 추가해주세요-!

2022-08-17 01:56 UTC, seatbelt92 commented on package.json
> +    "nodemon": "^2.0.19",
넵! 완료해서 다시 푸쉬했습니다.

2022-08-17 02:12 UTC, kyeongraekim approved these changes
LGTM!~

2022-08-17 02:13 UTC, merged