장바구니 기능 구현 - 품목삭제, 유저별 carts 테이블에 담은 상품 불러오기
wecode-bootcamp-korea/36-1st-wesely-backend pull request #4
Opened 2022-08-22 01:26 UTC by JeongJaeHa

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니 품목삭제, carts 테이블에 저장된 유저별 정보 불러오기

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. carts 테이블에 저장된 유저별 정보 불러오기
- 유저 번호(user_id) 입력 시 carts 테이블에 저장된 유저별 상품정보 로드
- 저장된 정보가 없는 경우 "carts empty" 메세지 반환
- 테스트 방법 : `/cart/user/:user_id 입력하여 진행` 

2. 장바구니(carts table) 품목삭제
- 장바구니 페이지 정보전달 시 전달된 carts 테이블의 id 입력시 해당 row 삭제

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 다중 INNER JOIN 시 정보를 불러오는 방법이 어려웠습니다.
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
**- ERD 구조변경으로 쿼리문 수정 예정입니다.**

2022-08-23 01:53 UTC, kyeongraekim requested changes

2022-08-23 01:53 UTC, kyeongraekim commented on controllers/cartController.js
> +const listAll = async (req, res) => {
- 노드 + 익스프레스 기반의 모듈 변수명은 getAllProductsInCart 와 같이 직관적으로 해당 모듈의 기능성을 드러내는 변수명을 작성해주시면 좋습니다. 현재 listAll의 내용이 다소 모호해보입니다.

2022-08-23 01:53 UTC, kyeongraekim commented on controllers/cartController.js
> +      res.status(204).json( {message: "DELETE SUCCESS"})
- 204 상태 코드를 반환하면 아마 뒤에 따라오는 메세지가 전달이 안될 것 입니다. 한 번 통신 시험을 해보고 해당 내용을 관찰해보세요~

2022-08-23 01:53 UTC, kyeongraekim commented on controllers/cartController.js
> +
- 불필요한 라인 Whitd Space를 지워주세요!~ 한 칸 정도의 공백이면 좋을 것 같네요!

2022-08-23 01:53 UTC, kyeongraekim commented on db/migrations/20220822071951_create_cloumn_patch_table.sql
> +
- migration을 건드리는 내용은 별도의 PR로 따로 올려주셔야 합니다. 데이터베이스 마이그레이션과 API 기능의 깃헙 푸시상 구분과 분리를 꼭 마음속에 염두해주세요!

2022-08-23 01:53 UTC, kyeongraekim commented on models/Database.js
> +	type: process.env.TYPEORM_CONNECTION,
type 부분에 불필요한 indentation white space가 보이네요!

2022-08-23 01:53 UTC, kyeongraekim commented on models/Database.js
> +const Database = new DataSource({
- 그리고 TypeORM 공식문서의 네이밍 원칙을 따라서 네이밍을 지어보는 것은 어떨까요?
- 추후에 다양한 데이터베이스의 커넥션이 이루어져야될 수 있는데 (예시, nosql의 mongoDB 등) 네이밍에서의 Database가 TypeORM을 통한 mysql 커넥션 하나로 수렴되듯이 보이면 추후 확장성이 결여되게 됩니다.

다음의 링크를 확인한 후 참고해주세요! https://typeorm.biunav.com/en/data-source.html#creating-a-new-datasource

2022-08-23 01:53 UTC, kyeongraekim commented on package.json
>      "mysql2": "^2.3.3",
- 패키지 관리측면에서 둘 중 하나의 드라이버를 install 해야 맞아보이는데 어떤 내용을 의도하신지 다시 한 번 확인해주세요~

2022-08-23 01:53 UTC, kyeongraekim commented on services/cartServices.js
> +  if ( cartIdCheck !== 1 ) {
현재 "=== 1", "===2" 이라고 일치여부를 정의 내린 내용은 1번 숫자에 하드 코딩 되어있다고 볼 수 있습니다. 상용화된 코드에서는 최대한 하드코딩을 지양한 후 변수로서 정의하여 사용해주셔야 하는데, 이 때 객체지향 프로그래밍에서는 enum이라는 클래스를 만들어서 사용합니다.

다만 자바스크립트에서는(타입스크립트는 제공을 하는 부분임) 해당 enum이라는 클래스 Syntax를 제공하지 않음으로 이와 최대한 유사한 환경의 변수를 설정하여서 사용해볼 수 있습니다. 다음의 링크와 코드 진행방식을 한 번 참고해주세요!
```javascript
const daysEnum = Object.freeze({
  monday: 0,
  tuesday: 1,
  wednesday: 2,
  thursday: 3,
  friday: 4,
  saturday: 5,
  sunday: 6
});
```
참고링크(1): https://www.30secondsofcode.org/articles/s/javascript-enum
참고링크(2): https://yorr.tistory.com/21

2022-08-23 01:53 UTC, kyeongraekim commented on services/cartServices.js
> +const deleteList = async ( id ) => {
위에 달아드린 가독성을 확보한 변수명에 맞게 deleteCartProductByxxxId 정도의 확실한 변수명을 전반적으로 한 번 고민해주세요!~

2022-08-23 05:08 UTC, JeongJaeHa commented on db/migrations/20220822071951_create_cloumn_patch_table.sql
> +
네 알겠습니다

2022-08-23 08:45 UTC, kyeongraekim requested changes

2022-08-23 08:45 UTC, kyeongraekim commented on models/cartDao.js
> +		errorFunc(404, "INVALID_DATA_INPUT")
indentation 한 번 수정해주세요~

2022-08-23 08:45 UTC, kyeongraekim commented on models/cartDao.js
> +		errorFunc(404, "INVALID_DATA_INPUT")
indentation 한 번 수정해주세요~

2022-08-23 08:45 UTC, kyeongraekim commented on services/cartServices.js
> +  };
const 와 Object.freeze의 차이점을 다음의 스택오버플로우 답안을 예시로 남겨드리겠습니다~ 단순한 변수 binding의 고정화 보다 그 내부 값들의 고정화까지도 진행해주세요!~

https://stackoverflow.com/a/33128023/16649759

```javascript
const daysEnum = Object.freeze({
  monday: 0,
  tuesday: 1,
  wednesday: 2,
  thursday: 3,
  friday: 4,
  saturday: 5,
  sunday: 6
});

2022-08-24 01:57 UTC, kyeongraekim requested changes

2022-08-24 01:57 UTC, kyeongraekim commented on services/cartServices.js
> +
- Enum의 존재에 대해서 이제 인지해주신 것 같네요! 사실 True, False 정도의 간단한 연산은 자바스크립트의 문법선에서의 Boolean을 이용해서 사용할 수는 있겠지만 Enum이 주는 좋은 장점이 있습니다. 그중 대표적인 예시로 내 마음대로 직관적인 언어로 내가 설정한 조건을 설정할 수 있다는 점입니다.
- 아래와 같이 설정한다면 더욱 의미 부여가 명확해지고 부정문(!==)이 아닌 긍정문(==)으로 논리를 살짝 바꾸어서 진행해볼 수 있겠네요! 

```javascript
  const cartCheckItem = await Number(Object.values(checkId[0])[0])
  const cartEnum = Object.freeze({
    exists: 1,
    notExists: 0
  });

  if ( cartCheckItem == cartEnum.notExists ) {
    const error = new Error( 'Cart empty' )
    error.statusCode = 409;
    throw error
  }
  });
```
- 다음 링크의 관점에서도 한 번 판단해보세요!~ https://betterprogramming.pub/dont-use-boolean-arguments-use-enums-c7cd7ab1876a
- 그리고 지금 전달해드린 Enum은 Ture False의 두 갈래 분기보다 3-4개 혹은 그 이상의 더많은 리스트 사용시 더 효과적인 결과를 낳습니다. 추후에 다양한 프로젝트에서 orderStatus 등에서 여러 조건에 대한 나열을 필요로 한 순간에 적극적으로 활용해보세요!~

2022-08-24 09:33 UTC, kyeongraekim approved these changes
LGTM!~

2022-08-24 09:33 UTC, merged