[ADD] products 전체, 카테고리별 불러오기
wecode-bootcamp-korea/36-1st-wesely-backend pull request #5
Opened 2022-08-23 04:12 UTC by seatbelt92

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 전체 및 카테고리별 불러오기 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 전체 불러오기
- 상품명, 이미지 등 게시될 데이터 전달
- 리뷰 개수 기준 정렬 적용
- 페이지네이션을 위한 offset, limit 쿼리파라미터 변수 설정

2. 카테고리별 상품 불러오기
- 상품명, 이미지 등 게시될 데이터 전달
- 리뷰 개수 기준 정렬 적용
- 카테고리 아이디 식별을 위한 category 쿼리 파라미터 변수 설정
- 페이지네이션을 위한 offset, limit 쿼리파라미터 변수 설정

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 서브쿼리로 작성했던 COUNT(rating)(리뷰개수) 로 정렬하기 위해서는 해당 컬럼이 있는 테이블을 FROM으로 불러오며, 기준 테이블로 설정하고, 필요한 정보들을 가진 것들을 outer left join을 사용해야 추후 GROUP BY 를 사용할 수 있다는 것을 알게 되었습니다.
- GTOUP BY를 썼을 때, 뒤에 HAVING을 사용하여 category 파라미터를 받았는데 오류가 발생하여, 앞쪽에 WHERE문을 작성하여 기능을 구현하며 쿼리문의 조건을 주는 방식에 대한 이해도를 높였습니다.
- 최종 적용된 쿼리문에는 적용되지 않았지만, 다양한 시도를 하며 서브쿼리는 JOIN을 하지 않은 테이블의 데이터도 가지고 올 수 있다는 것을 확인했습니다.
- WHERE문을 쓰는 순간 뒤에 확실한 조건값이 존재해야 하고, 그렇지 않을 경우에는 오류가 발생한다는 것을 토대로 category파라미터의 존재 여부에 따라 다른 쿼리문을 적용하고, Controlle단에서 if 문을 통해 구현해야 한다는 것을 알게 되었습니다.
-Dao 단의 두 가지 쿼리문을 동시에 불러오고 싶을 때는 JSON 형식으로 각각의 변수를 넣어줌으로써 구현하는 방법을 이해했습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-08-23 05:11 UTC, kyeongraekim requested changes

2022-08-23 05:11 UTC, kyeongraekim commented on models/productDao.js
> +        return await appDataSource.query(`SELECT
가독성을 위해 전반적으로 SELECT 시작 문을 아래로 line breaking 해도 좋을 것 같네요!

2022-08-23 05:11 UTC, kyeongraekim commented on models/productDao.js
> +        `);
- 현재 구조는 SQL Injection 과 관련된 보안에 취약한 변수 활용법입니다. 다음의 내용 중 data layer protection 란을 확인해 주신후 '?'를 활용한 데이터 주입으로 전반적인 Dao 단의 코드를 유도해주세요.
링크 바로가기: https://www.stackhawk.com/blog/node-js-sql-injection-guide-examples-and-prevention/

2022-08-23 05:11 UTC, kyeongraekim commented on controllers/productController.js
> +        const {category, offset, limit} = req.query
- 외부에서 받는 매개변수에 대한 변수명을 정확하게 표현해주세요. 아마 categoryId 값을 받을 것 같은데 categoryName, Id, sequence 등 다양한 정보를 받을 수 있는 기획이 있기 때문에 정확한 데이터 타입을 유도할 수 있는 변수명을 설정해주세요!~

2022-08-23 06:12 UTC, seatbelt92 commented on models/productDao.js
> +        return await appDataSource.query(`SELECT
네 반영했습니다.

2022-08-23 07:09 UTC, seatbelt92 commented on models/productDao.js
> +        `);
네 반영했습니다.

2022-08-23 09:03 UTC, seatbelt92 commented on controllers/productController.js
> +        const {category, offset, limit} = req.query
네 반영했습니다. (category > categoryId)

2022-08-23 09:13 UTC, kyeongraekim requested changes
SQL 선에서의 placeholder 사용을 인지해주셨으니 다음에 꼭 적용해보시고, 최소한의 Validation이 적용되어야 할 것 같네요! integer 값만 받아와서 인자로 넘겨줄 수 있게 정규표현식 validation을 controller단에서 통과시킨 후에, categoryId, offset, limit을 받아오는 것은 어떨까요?
아니면 기존에 존재하는 isNaN 메소드를 사용해도 좋을 것 같네요!~

2022-08-24 07:51 UTC, seatbelt92 commented
> SQL 선에서의 placeholder 사용을 인지해주셨으니 다음에 꼭 적용해보시고, 최소한의 Validation이 적용되어야 할 것 같네요! integer 값만 받아와서 인자로 넘겨줄 수 있게 정규표현식 validation을 controller단에서 통과시킨 후에, categoryId, offset, limit을 받아오는 것은 어떨까요? 아니면 기존에 존재하는 isNaN 메소드를 사용해도 좋을 것 같네요!~

2022-08-24 07:51 UTC, closed without merging