Feature/main page call
wecode-bootcamp-korea/36-1st-wesely-backend pull request #8
Opened 2022-08-24 08:07 UTC by seatbelt92

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인 페이지 불러오기 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리뷰 개수 기준으로 정렬된 9개 데이터 전송
2. 판매량 기준으로 정렬된 9개 데이터 전송 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- GROUP BY, ORDER BY, DESC, LIMIT를 활용하여 뽑아온 데이터를 그룹화하고, 원하는 기준 및 개수로 정렬하는 쿼리문에 대한 이해도를 높였습니다.
- 

<br />

## :: 기타 질문 및 특이 사항

2022-08-24 09:31 UTC, kyeongraekim requested changes
- 전체적으로 homepage에 입각한 home 과 관련된 일련의 layered pattern을 만들어주셨네요. 
- 하지만 세부 내용은 products와 관련된 내용으로 보여집니다. 백엔드의 API는 프론트엔드와 다르게 데이터적 관점에서 풀어주셔야 합니다. 전체 명칭을 products로 바꾸어 주시고, 혹시나 다른 팀원과 컨플릭트 날 수 있는 부분을 조심히 고려해가며 일을 진행해주세요!~

2022-08-24 10:21 UTC, seatbelt92 commented
> * 전체적으로 homepage에 입각한 home 과 관련된 일련의 layered pattern을 만들어주셨네요.
> * 하지만 세부 내용은 products와 관련된 내용으로 보여집니다. 백엔드의 API는 프론트엔드와 다르게 데이터적 관점에서 풀어주셔야 합니다. 전체 명칭을 products로 바꾸어 주시고, 혹시나 다른 팀원과 컨플릭트 날 수 있는 부분을 조심히 고려해가며 일을 진행해주세요!~

네, 라우터 취합하여 반영 후 커밋 다시 올리도록 하겠습니다.

2022-08-25 02:13 UTC, kyeongraekim requested changes

2022-08-25 02:13 UTC, kyeongraekim commented on controllers/productController.js
> +        const getTop9ByRating = await productService.getTop9ByRating();
- top 9으로 고정값을 변수명에 정해 놓는 것보다 유연하게 외부 요청에 그때 그때 대응할 수 있게 변경해주세요!~
offset limit 값을 전달 받으면 쉽게 해결할 수 있는 문제 같아 보이네요!~
- 따라서 변수명 자체도 getTop9BySales가 아닌, getPopularProducts 정도로 변경해주시고 추후의 확장성과 유연성을 적용해주세요.

2022-08-25 02:13 UTC, kyeongraekim commented on models/productDao.js
> +        LIMIT 9
- 위에 달아드린 리뷰를 참조해서 9로 하드코딩된 부분을 수정해주세요~

2022-08-25 02:13 UTC, kyeongraekim commented on routes/productRouter.js
> +router.get('/main', productController.getMain);
- 기획에서 사라진 내용이 보이네요!~ 삭제해주세요~

2022-08-25 09:20 UTC, kyeongraekim approved these changes

2022-08-25 09:20 UTC, merged